//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qu2SM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int adminid { get; set; }
        public string adminemail { get; set; }
        public string adminpasswd { get; set; }
        public string adminnickname { get; set; }
        public Nullable<int> role { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
