//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qu2SM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class follow
    {
        public int fid { get; set; }
        public int follower_id { get; set; }
        public int followed_id { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
