//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qu2SM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int mid { get; set; }
        public int senderid { get; set; }
        public int receiveid { get; set; }
        public string message1 { get; set; }
        public byte[] date { get; set; }
    }
}
