//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chatting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class picture
    {
        public int pid { get; set; }
        public byte[] picture1 { get; set; }
        public Nullable<int> contentid { get; set; }
    
        public virtual content content { get; set; }
    }
}
