//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chatting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.content = new HashSet<content>();
        }
    
        public int userid { get; set; }
        public string useremail { get; set; }
        public string usernickname { get; set; }
        public string username { get; set; }
        public string usersurname { get; set; }
        public Nullable<int> userage { get; set; }
        public string usercity { get; set; }
        public Nullable<int> userphone { get; set; }
        public string userjob { get; set; }
        public string password { get; set; }
        public byte[] userpp { get; set; }
        public string userrole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<content> content { get; set; }
    }
}
